rai:
  version: 0.2
resources:
  cpu:
    architecture: ppc64le
  network: false
commands:
  build_image:
    image_name: c3sr/docker.ppc64le:7.4.2
    dockerfile: "./Dockerfile"
    # no_cache: true
    push:
      push: true
